### passkey_
POST http://localhost:4000/authentication/login
Content-Type: application/json

{
  "credentials": ["root"]
}

### username_ password_
POST http://localhost:4000/authentication/login
Content-Type: application/json

{
  "credentials": ["user", "user"]
}

###
POST http://localhost:4000/authentication/refresh
Authentication-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2VudF9pZF8iOjEsInJlZnJlc2hfIjp0cnVlLCJpYXQiOjE2NTcwNzM3MDUsImV4cCI6MTY1NzA3NTYyNX0.gE7PfYIFwrlRJVuAVzQWdVlN43wEEErBlhOzBiGajjI
Content-Type: application/json

{
}

###
POST http://localhost:4000/authentication/protected
Authentication-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2VudF9pZF8iOjEsInJlZnJlc2hfIjp0cnVlLCJpYXQiOjE2NTcwNzM3MDUsImV4cCI6MTY1NzA3NTYyNX0.gE7PfYIFwrlRJVuAVzQWdVlN43wEEErBlhOzBiGajjI
Content-Type: application/json

{
}

###
POST http://localhost:4000/authentication/register
Content-Type: application/json

{
  "given_name_": "user",
  "surname_": "user",
  "email_": "user@user.com",
  "username_": "user",
  "password_": "user"
}
